In [14]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.37-py2.py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.0/73.0 kB 1.5 MB/s eta 0:00:0000:01
Collecting frozendict>=2.3.4
  Downloading frozendict-2.4.0-cp310-cp310-macosx_10_9_x86_64.whl (37 kB)
Requirement already satisfied: numpy>=1.16.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (1.23.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: requests>=2.31 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: pandas>=1.3.0 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (1.5.3)
Requirement already satisfied: html5lib>=1.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (1.1)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: pytz>=2022.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (2023.3)
Requirement already satisfied: lxml>=4.9.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from yfinance) (4.9.3)
Collecting appdirs>=1.4.4
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.1.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 17.5 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: soupsieve>1.2 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2.1.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.31->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.4)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.1-cp310-cp310-macosx_10_9_x86_64.whl size=253471 sha256=808d3a2207c135501de660c20667588ce365fbf19f06b092c3fb9a7c6be8e872
  Stored in directory: /Users/virajbansal/Library/Caches/pip/wheels/d7/35/5c/1374782be033462df5f40174d8d879519d64ed8c25a1977554
Successfully built peewee
Installing collected packages: peewee, multitasking, appdirs, frozendict, yfinance
Successfully installed appdirs-1.4.4 frozendict-2.4.0 multitasking-0.0.11 peewee-3.17.1 yfinance-0.2.37

In [15]:
import yfinance as yf

In [44]:
msft = yf.Ticker("A")
msft.info.get('marketCap')

42642432000

In [7]:
!python3 -m pip install setuptools

Requirement already satisfied: setuptools in /Users/virajbansal/.pyenv/versions/3.12.1/lib/python3.12/site-packages (69.2.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

In [2]:
!pip3 install pandas_datareader

Collecting pandas_datareader
  Using cached pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
Requirement already satisfied: requests>=2.19.0 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas_datareader) (2.31.0)
Requirement already satisfied: pandas>=0.23 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas_datareader) (1.5.3)
Requirement already satisfied: lxml in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas_datareader) (4.9.3)
Requirement already satisfied: pytz>=2020.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas>=0.23->pandas_datareader) (1.23.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from requests>=2.19.0->pandas_datareader) (2024.2.2)
Requirement already satisfied: six>=1.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas>=0.23->pandas_datareader) (1.16.0)
Installing collected packages: pandas_datareader
Successfully installed pandas_datareader-0.10.0

In [4]:
import pandas_datareader as dr
nasdq = dr.nasdaq_trader.get_nasdaq_symbols()

In [33]:
nasdq[nasdq['ETF'] == False]

,Nasdaq Traded,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
Symbol,,,,,,,,,,,
A,True,"Agilent Technologies, Inc. Common Stock",N,,False,100.0,False,NaN,A,A,False
AA,True,Alcoa Corporation Common Stock,N,,False,100.0,False,NaN,AA,AA,False
AACG,True,ATA Creativity Global - American Depositary Sh...,Q,G,False,100.0,False,N,NaN,AACG,False
AACI,True,Armada Acquisition Corp. I - Common Stock,Q,G,False,100.0,False,N,NaN,AACI,False
AACIU,True,Armada Acquisition Corp. I - Unit,Q,G,False,100.0,False,N,NaN,AACIU,False
...,...,...,...,...,...,...,...,...,...,...,...
ZXIET,True,IEX Test Company Test Symbol Three for IEX,V,,False,100.0,True,NaN,ZXIET,ZXIET,False
ZXYZ.A,True,Nasdaq Symbology Test Common Stock,Q,Q,False,100.0,True,N,NaN,ZXYZ.A,False
ZXZZT,True,NASDAQ TEST STOCK,Q,G,False,100.0,True,N,NaN,ZXZZT,False
ZYME,True,Zymeworks Inc. - Common Stock,Q,Q,False,100.0,False,N,NaN,ZYME,False
ZYXI,True,"Zynex, Inc. - Common Stock",Q,Q,False,100.0,False,N,NaN,ZYXI,False

In [34]:
nasdq_NoETF = nasdq[nasdq['ETF'] == False]

In [47]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (1.5.3)
Collecting pandas
  Downloading pandas-2.2.1-cp310-cp310-macosx_10_9_x86_64.whl (12.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.5/12.5 MB 2.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy<2,>=1.22.4 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: tzdata>=2022.7 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/virajbansal/mambaforge/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sagemaker 2.163.0 requires PyYAML==6.0, but you have pyyaml 5.4.1 which is incompatible.
pandasai 0.5.5 requires pandas==1.5.3, but you have pandas 2.2.1 which is incompatible.
Successfully installed pandas-2.2.1

In [49]:
import time
import pandas as pd

def get_sector_and_market_cap(ticker):
    time.sleep(1)  # Add a delay to avoid hitting the API rate limit
    print(ticker)
    ticker_info = yf.Ticker(ticker).info
    return [ticker_info.get('sector'), ticker_info.get('marketCap')]

# Assuming nasdq_NoETF is a DataFrame with ticker symbols as the index
nasdq_NoETF[['Sector', 'Market Cap']] = nasdq_NoETF.index.to_series().apply(get_sector_and_market_cap, result_type='expand')

TypeError: get_sector_and_market_cap() got an unexpected keyword argument 'result_type'

In [31]:
nasdq_NoETF

,Nasdaq Traded,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares,Sector
Symbol,,,,,,,,,,,,
A,True,"Agilent Technologies, Inc. Common Stock",N,,False,100.0,False,NaN,A,A,False,A
AA,True,Alcoa Corporation Common Stock,N,,False,100.0,False,NaN,AA,AA,False,AA
AACG,True,ATA Creativity Global - American Depositary Sh...,Q,G,False,100.0,False,N,NaN,AACG,False,AACG
AACI,True,Armada Acquisition Corp. I - Common Stock,Q,G,False,100.0,False,N,NaN,AACI,False,AACI
AACIU,True,Armada Acquisition Corp. I - Unit,Q,G,False,100.0,False,N,NaN,AACIU,False,AACIU
...,...,...,...,...,...,...,...,...,...,...,...,...
ZXIET,True,IEX Test Company Test Symbol Three for IEX,V,,False,100.0,True,NaN,ZXIET,ZXIET,False,ZXIET
ZXYZ.A,True,Nasdaq Symbology Test Common Stock,Q,Q,False,100.0,True,N,NaN,ZXYZ.A,False,ZXYZ.A
ZXZZT,True,NASDAQ TEST STOCK,Q,G,False,100.0,True,N,NaN,ZXZZT,False,ZXZZT
ZYME,True,Zymeworks Inc. - Common Stock,Q,Q,False,100.0,False,N,NaN,ZYME,False,ZYME
ZYXI,True,"Zynex, Inc. - Common Stock",Q,Q,False,100.0,False,N,NaN,ZYXI,False,ZYXI

In [7]:
import pandas as pd
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

# Use pandas to read the HTML table
sp500_table = pd.read_html(url)

# The first table on the page contains the S&P 500 list
sp500_df = sp500_table[0]

# Display the DataFrame
print(sp500_df[['Symbol', 'Security', 'GICS Sector']])

    Symbol            Security             GICS Sector
0      MMM                  3M             Industrials
1      AOS         A. O. Smith             Industrials
2      ABT              Abbott             Health Care
3     ABBV              AbbVie             Health Care
4      ACN           Accenture  Information Technology
..     ...                 ...                     ...
498    XYL          Xylem Inc.             Industrials
499    YUM         Yum! Brands  Consumer Discretionary
500   ZBRA  Zebra Technologies  Information Technology
501    ZBH       Zimmer Biomet             Health Care
502    ZTS              Zoetis             Health Care

[503 rows x 3 columns]

In [12]:
sp500_df['GICS Sector'].nunique()

11

In [10]:
sp500_df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952